Create new market-app-on-autoscaling module.
alibabacloud-automation/terraform-alicloud-market-app-on-autoscaling pull request #1
Opened 2020-02-26 12:21 UTC by zql-tqy

2020-02-26 13:03 UTC, Rich-yi commented on README-CN.md
> +  vswitch_id                 = data.alicloud_vpcs.default.vpcs.0.vswitch_ids.0
这些不用用data source之类的，写个值进去

2020-02-26 13:03 UTC, Rich-yi commented on README.md
> +  vswitch_id                 = data.alicloud_vpcs.default.vpcs.0.vswitch_ids.0
一样

2020-02-26 13:03 UTC, Rich-yi commented on outputs.tf
> +  value       = module.market_app_with_ecs_image.this_ecs_instance_image_id
这些不是list或者map的加个concat

2020-02-27 05:39 UTC, xiaozhu36 requested changes

2020-02-27 05:39 UTC, xiaozhu36 commented on main.tf
> +module "market_app_with_ecs_image" {
这个module中是不需要这个module的，而是应该把market_app_with_ecs_image中创建ecs 的过程替换成本module中使用autoscaling自动创建

2020-02-27 15:17 UTC, xiaozhu36 requested changes

2020-02-27 15:17 UTC, xiaozhu36 commented on .gitignore
> +.idea
把  *.log 也加上

2020-02-27 15:17 UTC, xiaozhu36 commented on README-CN.md
> +  security_group_ids    = ["sg-2ze0zgaj3hne6aiddmxx"]
脱敏

2020-02-27 15:17 UTC, xiaozhu36 commented on README-CN.md
> +  security_group_ids    = ["sg-2ze0zgaj3hne6aiddmxx"]
脱敏

2020-02-27 15:17 UTC, xiaozhu36 commented on .gitignore
> +.idea
把  *.log 也加上

2020-02-27 15:17 UTC, xiaozhu36 commented on README-CN.md
> +  instance_types        = "ecs.n1.small"
用 ecs.sn1ne.large

2020-02-27 15:17 UTC, xiaozhu36 commented on examples/complete/outputs.tf
> +output "this_url_of_market_application_with_dns" {
这个名称不对吧

2020-02-27 15:17 UTC, xiaozhu36 commented on main.tf
> +module "Autoscaling" {
market-autoscaling

2020-02-27 15:17 UTC, xiaozhu36 commented on README-CN.md
> +  instance_types        = "ecs.n1.small"
用 ecs.sn1ne.large

2020-02-27 15:17 UTC, xiaozhu36 commented on main.tf
> +module "Autoscaling" {
autoscaling

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +  description = "A default filter applied to retrieve existing vswitches by name regex. If not set, 'filter_with_name_regex' will be used."
这些 xxx_name_regex 都不需要

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +variable "filter_with_tags" {
这个filter_with_tags也不需要

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +variable "sg_tags" {
这个sg_tags也不需要

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +variable "vswitch_id" {
这个是不是跟前面的冲突了，我理解只支持一个vswitch_ids 就行吧

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +variable "create_scaling_configuration" {
所有的scaling的资源都共用一个 create_autoscaling  这一个开关

2020-02-27 15:17 UTC, xiaozhu36 commented on variables.tf
> +  default     = null
number 应该不能设置为 null吧

2020-02-28 14:22 UTC, xiaozhu36 requested changes

2020-02-28 14:22 UTC, xiaozhu36 commented on main.tf
> +  count            = local.create_slb_group ? 1 : 0
slb相关的都用 create_slb 或者use_existing_slb来控制

2020-02-28 14:22 UTC, xiaozhu36 commented on main.tf
> +  vswitch_id           = var.vswitch_id
这个改一下吧，既然要创建公网的slb，那么这个address_type就只能是 Internet，vswithc id也不需要了

2020-02-28 14:22 UTC, xiaozhu36 commented on variables.tf
> +  type        = bool
enable和active都写死为 true

2020-02-28 14:22 UTC, xiaozhu36 commented on variables.tf
> +variable "force_delete" {
这个也是true

2020-02-28 14:22 UTC, xiaozhu36 commented on variables.tf
> +variable "ecs_instance_name" {
这个别暴露了，根据这个场景生成一个

2020-02-29 09:22 UTC, xiaozhu36 requested changes

2020-02-29 09:22 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  product_keyword = "jenkins"
jenkins的改成 java 的

2020-02-29 09:22 UTC, xiaozhu36 approved these changes

2020-02-29 09:22 UTC, merged